#!/usr/bin/env python3
"""Create a validated ForgeOS platform-adapter skeleton."""
from __future__ import annotations

import argparse
import re
import shlex
from pathlib import Path

ID_RE = re.compile(r"^[a-z0-9][a-z0-9-]{1,31}$")

PROFILE = """# ForgeOS platform profile generated by tools/new-platform.py
[device]
id={device_id}
name={name}
family=linux-sdl

[ui]
screen_width={width}
screen_height={height}
screen_bpp={bpp}
fullscreen=1

[storage]
data_root=/mnt
rom_root=${{data_root}}/roms
home=${{data_root}}/forgeshell
tool_root=${{data_root}}/apps/forge-tools

[launcher]
provider={provider}
source={source}
fallback_command=/bin/true
frontend_value=forgeshell

[maintenance]
manifest=${{home}}/tools.tsv

[performance]
cpu_helper=

[power]
reboot=/sbin/reboot
poweroff=/sbin/poweroff

[input]
up=UP
down=DOWN
left=LEFT
right=RIGHT
accept=RETURN
back=ESCAPE
favorite=SPACE
options=RCTRL
page_left=TAB
page_right=BACKSPACE
start=LALT
select=LCTRL
power=LSHIFT

[joystick]
enabled=0
device=0
axis_x=0
axis_y=1
axis_threshold=16000
hat=0
up=-1
down=-1
left=-1
right=-1
accept=0
back=1
favorite=2
options=3
page_left=4
page_right=5
start=6
select=7
power=8

[labels]
accept=ENTER
back=ESC
favorite=SPACE
options=RCTRL
page_left=TAB
page_right=BKSP
start=ALT
select=CTRL
power=SHIFT

[capabilities]
battery=0
cpu_profiles=0
brightness=0
volume=0
safe_shutdown=0
storage_health=0
system_info=0
"""

TOOLS = """# id\ttitle\tmeta\tcommand\trequires
"""

SYSTEMS = """# Portable ForgeShell emulator manifest.
[system.example]
title=Example System
exec=/usr/bin/retroarch
params=-L /usr/lib/libretro/example_libretro.so [rom]
workdir=/usr/bin
romdir=${rom_root}/example
romexts=.zip,.rom
"""

BUILD_ENV = """# Select or implement a backend in tools/forge-build before enabling builds.
FORGE_BUILD_BACKEND=unimplemented
FORGE_DEVICE_ID={device_id}
FORGE_DEVICE_NAME={quoted_name}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("device_id")
    parser.add_argument("--name", required=True)
    parser.add_argument("--resolution", default="320x240")
    parser.add_argument("--bpp", type=int, choices=(16, 24, 32), default=16)
    parser.add_argument("--provider", choices=("gmenu2x", "forge-manifest"), default="forge-manifest")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    if not ID_RE.fullmatch(args.device_id):
        parser.error("device_id must use lowercase letters, digits, and hyphens")
    if not args.name.strip() or any(char in args.name for char in "\r\n\0"):
        parser.error("name must be a non-empty single line")
    try:
        width_text, height_text = args.resolution.lower().split("x", 1)
        width, height = int(width_text), int(height_text)
    except ValueError:
        parser.error("resolution must be WIDTHxHEIGHT")
    if width < 160 or height < 120:
        parser.error("resolution must be at least 160x120")
    destination = args.root / "platforms" / args.device_id
    if destination.exists():
        parser.error(f"platform already exists: {destination}")
    destination.mkdir(parents=True)
    source = "${data_root}/gmenu2x/sections/emulators:${data_root}/gmenu2x/sections/cores" \
        if args.provider == "gmenu2x" else "${home}/systems.ini"
    (destination / "platform.ini").write_text(PROFILE.format(
        device_id=args.device_id, name=args.name, width=width, height=height,
        bpp=args.bpp, provider=args.provider, source=source), encoding="utf-8")
    (destination / "tools.tsv").write_text(TOOLS, encoding="utf-8")
    if args.provider == "forge-manifest":
        (destination / "systems.ini").write_text(SYSTEMS, encoding="utf-8")
    (destination / "build.env").write_text(BUILD_ENV.format(
        device_id=args.device_id, quoted_name=shlex.quote(args.name)), encoding="utf-8")
    (destination / "README.md").write_text(
        f"# {args.name} adapter\n\nComplete the checklist in `docs/PORTING.md`, implement the build backend and runtime tools, "
        f"then enable only capabilities that have working implementations. Run `./forge-build {args.device_id} --doctor` before building.\n", encoding="utf-8")
    print(destination)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
